### ISSUE TITLE
If a project is using older version of babelify then source is not transformed

### ISSUE THREAD

**Issue by mikkoh** [Jam3/camera-spin#1]
Currently on the project we're working on the source for this module isn't being transformed properly as on the project an older version of `babel` is being used.

It's yucky but maybe the source should be built and `"main"` is the built version. Tower of Babel is falling down.

**Comment by hughsk** [comment]
Hmm, that shouldn't be the case since transforms are applied locally per module. Are you using `camera-spin@1.0.4` or `camera-spin@1.0.3`? The former package should be fixed, but if you're still having issues I'll switch it over to use just the built version :)

**Comment by hughsk** [comment]
Ah! My bad, a dependency was missing: https://github.com/Jam3/camera-spin/commit/5848a8d927f06a9bc932a21e900eb56aa194fc21
